import { TargetData } from 'src/types/custom';

// const data = {
//   id: null,
//   meter: 0,
//   maxSteps: 12,
//   overhead: 0,
//   resolved: false,
//   stats: {
//     hp: { current: 10, max: 10 },
//     ep: { current: 10, max: 10 },
//     attack: { current: 1, max: 1 },
//     defense: { current: 1, max: 1 },
//     status: [],
//   },
// } as TargetData;

const monsters = {
  bat: {
    name: 'Bat',
    desc: 'flying scavenger',
    image: 'bat',
    attack: 0,
    defense: 0,
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  beholder: {
    name: 'Beholder',
    desc: 'evil flying eye',
    attack: 0,
    defense: 0,
    image: 'beholder',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  brute: {
    name: 'Brute',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'brute',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  cowled: {
    name: 'Cowled',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'cowled',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  cyclop: {
    name: 'Cyclop',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'cyclop',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  darknight: {
    name: 'Dark Knight',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'darknight',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  delighted: {
    name: 'Delighted',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'delighted',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  dragon: {
    name: 'Dragon',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'dragon',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  dwarf1: {
    name: 'Dwarf',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'dwarf-1',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  dwarf2: {
    name: 'Battle Dwarf',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'dwarf-2',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  elf: {
    name: 'Dark Elf',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'elf',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  executioner: {
    name: 'Executioner',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'executioner',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  goblin: {
    name: 'Goblin',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'goblin',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  golem: {
    name: 'Golem',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'golem',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  ifrit: {
    name: 'Ifrit',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'ifrit',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  imp: {
    name: 'Imp',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'imp',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  litch: {
    name: 'Litch',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'litch',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  minion1: {
    name: 'Minion',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'minion-1',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  minion2: {
    name: 'Demon',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'minion-2',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  overlord: {
    name: 'Overlord',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'overlord',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  psionic: {
    name: 'Psionic',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'psionic',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  pyromaniac: {
    name: 'Pyromaniac',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'pyromaniac',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  slime: {
    name: 'Slime',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'slime',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
  troglodyte: {
    name: 'Troglodyte',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'troglodyte',
    maxSteps: 10,
    attitude: 'neutral',
    cards: [],
  },
};

export type MonsterID = keyof typeof monsters;
export type Monster = (typeof monsters)[MonsterID];
const monsterIds: MonsterID[] = Object.keys(monsters) as MonsterID[];

export default {
  monsterIds,
  monsters,
};

// ======================================================
// getters

export const getMonstersArray = (): string[] => {
  return Object.keys(monsters);
};
