const monsters = {
  // hero: {
  //   name: 'Hero',
  //   desc: 'An image of yourself',
  //   attack: 0,
  //   defense: 0,
  //   image: 'bat',
  //   maxSteps: 12,
  // },

  bat: {
    name: 'Bat',
    desc: 'flying scavenger',
    attack: 0,
    defense: 0,
    image: 'bat',
    maxSteps: 8,
  },
  beholder: {
    name: 'Beholder',
    desc: 'evil flying eye',
    attack: 0,
    defense: 0,
    image: 'beholder',
    maxSteps: 8,
  },
  brute: {
    name: 'Brute',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'brute',
    maxSteps: 8,
  },
  cowled: {
    name: 'Cowled',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'cowled',
    maxSteps: 8,
  },
  cyclop: {
    name: 'Cyclop',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'cyclop',
    maxSteps: 8,
  },
  darknight: {
    name: 'Dark Knight',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'darknight',
    maxSteps: 8,
  },
  delighted: {
    name: 'Delighted',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'delighted',
    maxSteps: 8,
  },
  dragon: {
    name: 'Dragon',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'dragon',
    maxSteps: 8,
  },
  dwarf1: {
    name: 'Dwarf',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'dwarf-1',
    maxSteps: 8,
  },
  dwarf2: {
    name: 'Battle Dwarf',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'dwarf-2',
    maxSteps: 8,
  },
  elf: {
    name: 'Dark Elf',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'elf',
    maxSteps: 8,
  },
  executioner: {
    name: 'Executioner',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'executioner',
    maxSteps: 8,
  },
  goblin: {
    name: 'Goblin',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'goblin',
    maxSteps: 8,
  },
  golem: {
    name: 'Golem',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'golem',
    maxSteps: 8,
  },
  ifrit: {
    name: 'Ifrit',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'ifrit',
    maxSteps: 8,
  },
  imp: {
    name: 'Imp',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'imp',
    maxSteps: 8,
  },
  litch: {
    name: 'Litch',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'litch',
    maxSteps: 8,
  },
  minion1: {
    name: 'Minion',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'minion-1',
    maxSteps: 8,
  },
  minion2: {
    name: 'Demon',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'minion-2',
    maxSteps: 8,
  },
  overlord: {
    name: 'Overlord',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'overlord',
    maxSteps: 8,
  },
  psionic: {
    name: 'Psionic',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'psionic',
    maxSteps: 8,
  },
  pyromaniac: {
    name: 'Pyromaniac',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'pyromaniac',
    maxSteps: 8,
  },
  slime: {
    name: 'Slime',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'slime',
    maxSteps: 8,
  },
  troglodyte: {
    name: 'Troglodyte',
    desc: '',
    attack: 0,
    defense: 0,
    image: 'troglodyte',
    maxSteps: 8,
  },
};

export type MonsterID = keyof typeof monsters;
export type Monster = (typeof monsters)[MonsterID];
const monsterIds: MonsterID[] = Object.keys(monsters) as MonsterID[];

export default {
  monsterIds,
  monsters,
};

// ======================================================
// getters

export const getMonstersArray = (): string[] => {
  return Object.keys(monsters);
};
